### ISSUE TITLE
API 명세서 관련 이슈

### ISSUE THREAD

**Issue by rkdgusdnr99** [haechanlee96/Post-Lv2#3]
LV2 과제의
명세서와 맞지 않는 입력 방식입니다.
{
"username" : "oooooo", 
"password" : "xxxxxx"
}
방식으로 입력이 되어야 한다고 생각합니다

**Comment by rkdgusdnr99** [comment]
아닙니다 착각했습니다 죄송합니다 ㅜㅜ

**Comment by haechanlee96** [comment]
네넵
